name: My CI Workflow

on:
  push:
    branches:
      - master
      - development

jobs:
  my_build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!





