name: CI
on:
  push:
    branches: [ "main" ]

jobs:
  my_build_job:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v3
      name: Run a one-line script
      run: echo Hello, world!




